exam_prep/preparation_project/preparation_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("preparation_project.web.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

exam_prep/preparation_project/preparation_project/web/urls.py
from django.urls import path
from preparation_project.web import views

"""
3. Routes
• http://localhost:8000/ - home page
• http://localhost:8000/album/add/ - add album page
• http://localhost:8000/album/details/<id>/ - album details page
• http://localhost:8000/album/edit/<id>/ - edit album page
• http://localhost:8000/album/delete/<id>/ - delete album page
• http://localhost:8000/profile/details/ - profile details page
• http://localhost:8000/profile/delete/ - delete profile page
"""


urlpatterns = [
    path("", views.home_page, name="home page"),
    path("album/add/", views.add_album, name="add album page"),
    path("album/details/<int:id>/", views.album_details, name="album details page"),
    path("album/edit/<int:id>/", views.album_edit, name="edit album page"),
    path("album/delete/<int:id>/", views.album_delete, name="delete album page"),

    path("profile/details/", views.profile_details, name="profile details page"),
    path("profile/delete/", views.profile_delete, name="delete profile page"),

]

exam_prep/preparation_project/preparation_project/web/models.py
from django.db import models
from django.core.validators import MinLengthValidator, MaxLengthValidator
from .validators import (
    # MaxLengthClassValidator,
    TextContainsOnlyAlphaNumericAndUnderscoreValidator,
    CustomFloatPositiveValidator
)

# Create your models here.
"""
Profile
o Username
    ▪ Character field, required.
    ▪ It should have at least 2 characters and maximum - 15 characters.
    ▪ The username can consist only of letters, numbers, and underscore ("_"). 
    Otherwise, raise a ValidationError with the message: "Ensure this value contains only letters,
    numbers, and underscore."
o Email
    ▪ Email field, required.
o Age
    ▪ Integer field, optional.
    ▪ The age cannot be below 0
"""


class Profile(models.Model):
    username = models.CharField(
        blank=False,
        null=False,
        validators=[
            MinLengthValidator(2),
            #MaxLengthClassValidator(15),
            MaxLengthValidator(15),
            TextContainsOnlyAlphaNumericAndUnderscoreValidator()
        ]
    )
    email = models.EmailField(blank=False, null=False)
    age = models.PositiveIntegerField(blank=True, null=True)

    def __str__(self):
        return self.username


"""
Album Name
    ▪ Character field, required.
    ▪ All album names must be unique.
    ▪ It should consist of a maximum of 30 characters.
o Artist
    ▪ Character field, required.
    ▪ It should consist of a maximum of 30 characters.
    
o Genre
    ▪ Char field, required.
    ▪ It should consist of a maximum of 30 characters.
    ▪ The choices are "Pop Music", "Jazz Music", "R&B Music", "Rock Music",
    "Country Music", "Dance Music", "Hip Hop Music", and "Other".
o Description
    ▪ Text field, optional.
o Image URL
    ▪ URL field, required.
o Price
    ▪ Float field, required.
    ▪ The number of decimal places of the price should not be specified in the database.
    ▪ The price cannot be below 0.0
"""


class Album(models.Model):
    GENRE_CHOICES = [
        ("pop", "Pop Music"),
        ("jazz", "Jazz Music"),
        ("rnb", "R&B Music"),
        ("rock", "Rock Music"),
        ("country", "Country Music"),
        ("dance", "Dance Music"),
        ("hiphop", "Hip Hop Music"),
        ("other", "Other")
    ]

    album_name = models.CharField(
        blank=False, null=False, max_length=30, unique=True
    )
    artist = models.CharField(
        blank=False, null=False, max_length=30
    )
    genre = models.CharField(
        blank=False, null=False,
        max_length=30, choices=GENRE_CHOICES
    )

    description = models.TextField(blank=True, null=True)
    image_url = models.URLField(blank=False, null=False)
    price = models.FloatField(
        blank=False, null=False,
        validators=[CustomFloatPositiveValidator()]
    )
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)

exam_prep/preparation_project/preparation_project/web/forms.py
from django import forms
from .models import Profile, Album


class ProfileModelForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'
        widgets = {
            'username': forms.TextInput(attrs={
                'placeholder': 'Username'
            }),
            'email': forms.EmailInput(attrs={
                'placeholder': 'Email'
            }),
            'age': forms.NumberInput(attrs={
                'placeholder': 'Age'
            })
        }


class AlbumModelForm(forms.ModelForm):
    class Meta:
        model = Album
        fields = '__all__'
        exclude = ['profile']

        widgets = {
            'album_name': forms.TextInput(attrs={
                'placeholder': 'Album'
            }),
            'artist': forms.TextInput(attrs={
                'placeholder': 'Artist'
            }),
            'genre': forms.Select(attrs={
                'placeholder': 'Genre'
            }),
            'description': forms.Textarea(attrs={
                'placeholder': 'Description'
            }),
            'image_url': forms.URLInput(attrs={
                'placeholder': 'Image URL'
            }),
            'price': forms.NumberInput(attrs={
                'placeholder': 'Price'
            })
        }
        labels = {
            "image_url": "Image URL"
        }


class DeleteAlbumModelForm(AlbumModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for _, field in self.fields.items():
            field.widget.attrs = {
                'readonly': 'readonly'
            }

exam_prep/preparation_project/preparation_project/web/views.py
from django.shortcuts import render, redirect
from .models import Profile, Album
from .forms import ProfileModelForm, AlbumModelForm, DeleteAlbumModelForm


# Create your views here.
def home_page(request):
    # profile = Profile.objects.all().firsts() - equal
    profile = Profile.objects.first()
    albums = Album.objects.all()
    form = ProfileModelForm()

    if request.method == "POST":
        form = ProfileModelForm(request.POST)
        if form.is_valid():
            form.save()

            return redirect(request.path_info)

    context = {"albums": albums, "add_form": form}

    if profile:
        template = "web/home-with-profile.html"
    else:
        template = "web/home-no-profile.html"

    return render(request, template_name=template, context=context)


def add_album(request):
    profile = Profile.objects.first()

    if not profile:
        redirect('home page')

    form = AlbumModelForm(request.POST or None)

    if form.is_valid():
        album = form.save(commit=False)
        album.profile = profile
        album.save()
        return redirect("home page")

    context = {"profile": profile, "add_form": form}

    return render(request, "web/add-album.html", context)


def album_details(request, id):
    profile = Profile.objects.first()
    context = {"profile": profile, "album": Album.objects.get(id=id)}

    return render(request, "web/album-details.html", context)


def album_edit(request, id):
    profile = Profile.objects.first()
    album = Album.objects.get(id=id)
    form = AlbumModelForm(instance=album)

    context = {"edit_form": form, "profile": profile, "album": album}

    if request.method == "POST":
        form = AlbumModelForm(request.POST, instance=album)
        if form.is_valid():
            form.save()
            return redirect("home page")

    return render(request, "web/edit-album.html", context)


def album_delete(request, id):
    profile = Profile.objects.first()
    album = Album.objects.get(id=id)
    form = DeleteAlbumModelForm(instance=album)

    if request.method == "POST":
        form = DeleteAlbumModelForm(request.POST, instance=album)
        if form.is_valid():
            album.delete()
            return redirect("home page")

    context = {"delete_form": form, "profile": profile, "album": album}

    return render(request, "web/delete-album.html", context)


def profile_details(request):
    context = {
        "profile": Profile.objects.first()
    }

    return render(request, "web/profile-details.html", context)


def profile_delete(request):
    profiles = Profile.objects.all()
    if request.method == 'POST':
        profiles.delete()
        return redirect('home page')

    return render(request, "web/profile-delete.html")

exam_prep/preparation_project/templates/web/add-album.html
{% extends 'web/base.html' %}
{% load static %}

{% block other_pages %}
<!--Create Page-->
<section class="createPage">

    <form {% url 'add album page' %} method="post">
        <fieldset>
            <legend>Add Album</legend>
            <div class="container">
                {% csrf_token %}
                {{ add_form }}
                <!-- Button for Adding Album -->
                <button class="add-album" type="submit">Add New Album</button>
            </div>
        </fieldset>
    </form>
</section>
{% endblock %}

exam_prep/preparation_project/templates/web/album-details.html
{% extends 'web/base.html' %}
{% load static %}

{% block other_pages %}
<!--Details Page-->
<section id="detailsPage">
    <div class="wrapper">

        <div class="albumCover">
            <!-- Album Image -->
            <img src="{{ album.image_url }}" alt="Cover Image">
        </div>

        <div class="albumInfo">

            <div class="albumText">
                <!-- Album Info -->
                <h1>Name: {{  album.album_name }}</h1>
                <h3>Artist: {{ album.artist }}</h3>
                <h4>Genre: {{ album.genre }}</h4>
                <h4>Price: ${{ album.price|floatformat:2 }}</h4>
                <p>Description: {{ album.description }}</p>
            </div>

            <div class="actionBtn">
                <!-- Album Buttons -->
                <a href="{% url 'edit album page' id=album.id %}" class="edit">Edit</a>
                <a href="{% url 'delete album page' id=album.id %}" class="remove">Delete</a>
            </div>

        </div>
    </div>
</section>
{% endblock %}

exam_prep/preparation_project/templates/web/base.html
{% load static %}
{% load tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8"/>
    <title>My Music App</title>
    <!-- Static Load -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
</head>

<body>
<div id="box">

    {# This way we can avoid adding the Profile to the context each time! A custom tag #}
    {% custom_navigation %}

    <!-- Main Content -->
    {% block main_content_no_profile %}
    {% endblock %}

    {% block main_content_profile %}
    {% endblock %}

    {% block other_pages %}
    {% endblock %}

    <!-- Footer -->
    <footer>
        <div>
            &copy;SoftUni Team 2022. All rights reserved.
        </div>
    </footer>
    <!-- End Footer -->

</div>
</body>
</html>

exam_prep/preparation_project/templates/web/delete-album.html
{% extends 'web/base.html' %}
{% load static %}

{% block other_pages %}

<!--Edit Page-->
<section class="editPage">
    <form action="{% url 'delete album page' id=album.id %}" method="post">
        <fieldset>
            <legend>Delete Album</legend>
            <div class="container">

                <!-- Form for Deleting an Album -->
                {% csrf_token %}
                {{ delete_form }}
                <!-- Button for Deleting an Album -->
                <button class="delete-album" type="submit">Delete Album</button>
            </div>
        </fieldset>
    </form>
</section>
{% endblock %}

exam_prep/preparation_project/templates/web/edit-album.html
{% extends 'web/base.html' %}
{% load static %}

{% block other_pages %}

<!--Edit Page-->
<section class="editPage">
    <form method="post" action="{% url 'edit album page' id=album.id %}">
        <fieldset>
            <legend>Edit Album</legend>
            <div class="container">

                <!-- Form for Editing Album -->
                {% csrf_token %}
                {{ edit_form }}

                <!-- Button for Editing Album -->
                <button class="edit-album" type="submit">Edit Album</button>
            </div>
        </fieldset>
    </form>
</section>

{% endblock %}

exam_prep/preparation_project/templates/web/home-no-profile.html
<!--Home Page-->
{% extends 'web/base.html' %}
{% load static %}


{% block main_content_no_profile %}
<div class="container-inline">
    <section id="welcomePage">
        <div id="welcome-message">
            <h1>Welcome to</h1>
            <h1>My Music App!</h1>
        </div>
        <div class="music-img">
            <img src="{% static 'images/musicIcons.webp' %}" alt="music-icon">
        </div>
    </section>

    <!-- Registration -->
    <section id="registerPage">

        <form action="{% url 'home page' %}" method="post">
            <fieldset>
                <legend>Profile</legend>
                <!-- Form for Registration -->
                {% csrf_token %}
                {{ add_form }}
                <!-- Button to Create Profile -->
                <button type="submit" class="register">Enter</button>
            </fieldset>
        </form>
    </section>
</div>
{% endblock %}

exam_prep/preparation_project/templates/web/home-with-profile.html
{% extends "web/base.html" %}
{% load static %}

{% block main_content_profile %}
<!-- Catalog with Albums-->
<section id="catalogPage">

    <!--  If No albums in catalog -->
    {% if not albums %}
    <p>No Albums in Catalog!</p>
    {% else %}
    <!-- If albums in catalog -->
    <h1>All Albums</h1>

    {% for album in albums %}
    <!-- Card-Box in catalog -->
    <div class="card-box">
        <img src="{{ album.image_url }}" alt="Cover Image">
        <div>
            <div class="text-center">
                <p class="name">Name: {{ album.album_name }}</p>
                <p class="artist">Artist: {{ album.artist }}</p>
                <p class="genre">Genre: {{ album.genre }}</p>
                <p class="price">Price: ${{ album.price|floatformat:2 }}</p>
            </div>
            <div class="btn-group">
                <a href="{% url 'album details page' id=album.id %}">Details</a>
            </div>
        </div>
    </div>
    <!-- End Card-Box in catalog -->
    {% endfor %}

    {% endif %}
</section>
{% endblock %}

exam_prep/preparation_project/templates/web/profile-delete.html
{% extends 'web/base.html' %}
{% load static %}

{% block other_pages %}

<!-- Delete Profile Page-->
<section id="detailsPage">
    <div class="wrapper">
        <div class="profileText">

            <!-- Delete Profile Form -->
            <h1>Are you sure you want to delete your profile?</h1>
            <form method="post" {% url 'delete profile page' %}>
                <!-- Confirm Button -->
                {% csrf_token %}
                <button class="delete-profile" type="submit">Delete</button>
            </form>
            <!-- End Delete Profile Form -->

        </div>
    </div>
</section>

{% endblock %}

exam_prep/preparation_project/templates/web/profile-details.html
{% extends 'web/base.html' %}
{% load static %}

{% block other_pages %}
<!--Details Page-->
<section id="detailsPage">
    <div class="wrapper">
        <div class="profilePage">
            <img src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png"
                 alt="Profile Image">
        </div>

        <div class="profileText">
            <!-- Profile Info -->
            <h1>Username: {{ profile.username }}</h1>
            <h1>Email: {{ profile.email }}</h1>
            <h1>Age: {{ profile.age }}</h1>
            <h1>Albums: {{ profile.album_set.count }}</h1>
        </div>

        <div class="actionBtn">
            <!-- Button for Deleting the Profile -->
            <a href="{% url 'delete profile page' %}" class="remove">Delete</a>
        </div>

    </div>
</section>
{% endblock %}